---
- name: Cisco IOS Facts
  hosts: cisco
  tasks:
    - ios_facts:
        provider: "{{ ssh_provider }}"

- name: NX-OS Facts
  hosts: nxos
  tasks:
    - nxos_facts:
        provider: "{{ nxapi_provider }}"

- name: Print out model
  hosts: cisco:nxos
  tasks:
    - debug:
        var: ansible_net_model
