---
- name: Variables, Debug, and Set Fact
  hosts: local
  vars:
    ntp1: 1.1.1.1
    ntp2: 1.1.1.2
    dns1: 8.8.8.8
    dns2: 8.8.4.4
    domain: bogus.com
  tasks:
    - name: Print out DNS servers
      debug:
        msg: "{{ dns1 }} {{ dns2 }}"

    - set_fact:
        dns3: 4.4.2.2
    
    - name: Print out third DNS server
      debug:
        var: dns3
