---
- name: Configure General Items
  hosts: pynet-rtr1
  tasks:
    - ios_config:
        provider: "{{ ssh_provider }}"
        lines:
          - "ip name-server {{ dns1 }}"
          - "ip name-server {{ dns2 }}"
          - "ntp server {{ ntp1 }}"
          - "ntp server {{ ntp2 }}"
          - "ip domain name {{ domain }}"
